// <auto-generated />
using System;
using Jeremy_Castillo_Ap1_p2.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Jeremy_Castillo_Ap1_p2.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20220322212244_inicial")]
    partial class inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.3");

            modelBuilder.Entity("EntradaEmpacadoProductos", b =>
                {
                    b.Property<int>("EntradaEmpacadosId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("entradaEmpacadosProductoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("EntradaEmpacadosId", "entradaEmpacadosProductoId");

                    b.HasIndex("entradaEmpacadosProductoId");

                    b.ToTable("EntradaEmpacadoProductos");
                });

            modelBuilder.Entity("Jeremy_Castillo_Ap1_p2.Entidades.EntradaEmpacado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CantidadProducido")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CantidadUtilizado")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Concepto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductoProducido")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductoUtilizado")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("EntradaEmpacado");
                });

            modelBuilder.Entity("Jeremy_Castillo_Ap1_p2.Entidades.Productos", b =>
                {
                    b.Property<int>("ProductoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Costo")
                        .HasColumnType("REAL");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Existencia")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaCaducidad")
                        .HasColumnType("TEXT");

                    b.Property<float>("Ganancia")
                        .HasColumnType("REAL");

                    b.Property<float>("Peso")
                        .HasColumnType("REAL");

                    b.Property<double>("Precio")
                        .HasColumnType("REAL");

                    b.Property<double>("ValorInventario")
                        .HasColumnType("REAL");

                    b.HasKey("ProductoId");

                    b.ToTable("Productos");
                });

            modelBuilder.Entity("Jeremy_Castillo_Ap1_p2.Entidades.ProductosDetalle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cantidad")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Concepto")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descripcion")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Precio")
                        .HasColumnType("TEXT");

                    b.Property<string>("Presentacion")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProductoId");

                    b.ToTable("ProductosDetalles");
                });

            modelBuilder.Entity("EntradaEmpacadoProductos", b =>
                {
                    b.HasOne("Jeremy_Castillo_Ap1_p2.Entidades.EntradaEmpacado", null)
                        .WithMany()
                        .HasForeignKey("EntradaEmpacadosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Jeremy_Castillo_Ap1_p2.Entidades.Productos", null)
                        .WithMany()
                        .HasForeignKey("entradaEmpacadosProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Jeremy_Castillo_Ap1_p2.Entidades.ProductosDetalle", b =>
                {
                    b.HasOne("Jeremy_Castillo_Ap1_p2.Entidades.Productos", null)
                        .WithMany("productosDetalle")
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Jeremy_Castillo_Ap1_p2.Entidades.Productos", b =>
                {
                    b.Navigation("productosDetalle");
                });
#pragma warning restore 612, 618
        }
    }
}
